require './Addition.rb'
require './Division.rb'
require './IntegerNode'
require './Multiplication.rb'
require './Note'
require './Motif'
require './rdparse'
require './RootNode'
require './Segment'
require './Silence'
require './StringNode'
require './Structure'
require './Subtraction.rb'

