require './Addition.rb'
require './Division.rb'
require './IntegerNode'
require './Motif'
require './Multiplication.rb'
require './Note'
require './NoteIdToken'
require './Print'
require './rdparse'
require './RepeatNode' #TODO
require './Segment'
require './Silence'
require './StringNode'
require './Structure'
require './Subtraction.rb'
require './VariableList'
require './VariableNode'

